module.exports={
    exchange:'binance',
    category: "linear",
    symbol: "BTCUSDT",
    side: "Buy",
    orderType: "Limit",
    qty: "1",
    price: "25000",
    timeInForce: "GTC",
    positionIdx: 0,
    orderLinkId: "usdt-test-01",
    reduceOnly: false,
    takeProfit: "28000",
    stopLoss: "20000",
    tpslMode: "Partial",
    tpOrderType: "Limit",
    slOrderType: "Limit",
    tpLimitPrice: "27500",
    slLimitPrice: "20500",
    shortPeriod:"10",
    longPeriod :"20",
    stopLossPercentage: "1",
    trailingStopDistance:"1",
    rsiPeriod:10,
    overBoughtThreshold:70,
    overSoldThreshold:30,
    buyThreshold : 1,
    leverage: 10,
    riskPercentage:1,
    maxDrawdownPercentage:0.1,
    cronPattern: "* * * * *",
}